### ISSUE TITLE
Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout when upgrading to 1.0.9

### ISSUE THREAD

**Issue by summera** [turbolinks/turbolinks-android#107]
I'm trying to update the library to `1.0.9` but keep getting a fatal exception on boot. I've tried clearing the cache and project - still happening. `1.0.8` is working for me.

```
2019-01-31 08:43:42.324 10719-10719/com.my.app.android.development E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.app.android.development, PID: 10719
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
        at com.basecamp.turbolinks.TurbolinksSession.getDefault(TurbolinksSession.java:191)
        at com.my.app.MainActivity.onCreate(MainActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout" on path: DexPathList[[zip file ...]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.basecamp.turbolinks.TurbolinksSession.getDefault(TurbolinksSession.java:191) 
        ...
```

**Comment by JimChen** [comment]
@summera looks like the androidx is not working at your project. did you add android.useAndroidX=true
android.enableJetifier=true
to your grandle.properties file and add correct implementation statement at the module bundle.gradle file?

**Comment by lateplate** [comment]
This doesn't appear to be Turbolinks specific (see previous comment about AndroidX packaging).

**Comment by 1uokun** [comment]
`app/build.gradle`
```diff
dependencies {
    ...
+   implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

}
```
